In [88]:
import numpy as np

w1_init = np.array([[1, 1, 1, 1], [1, 1, 2, 1], [1, 1, 1, 1]])
b1_init = np.array([[1], [1], [1]])
w2_init = np.array([[1, 4, 1], [1, 1, 1]])
b2_init = np.array([[1], [1]])
w3_init = np.array([[1, 1], [3, 1], [1, 1]])
b3_init = np.array([[1], [1], [1]])

activation_function = lambda x: np.tanh(0.5*x - 2)
activation_derivative = lambda x: 0.5 - 0.5*(np.tanh(0.5*x - 2))**2

error_derivative = lambda t, o: -(t-o)

x1 = np.array([[1], [1], [1], [1]])
x2 = np.array([[1], [0], [0], [-1]])

t1 = np.array([[-1], [1], [-1]])
t2 = np.array([[1], [-1], [-1]])

learning_rate = 0.1

In [89]:
def forward_prop(x0, w1, b1, w2, b2, w3, b3, activation, i=6):
    # Layer 1
    z1 = w1@x0 + b1
    x1 = activation(z1)

    # Layer 2
    z2 = w2@x1 + b2
    x2 = activation(z2)

    # Layer 3
    z3 = w3@x2 + b3
    x3 = activation(z3)
    outputs = [x0, z1, x1, z2, x2, z3, x3]
    return outputs[i]

In [90]:
forward_prop_init = lambda x, i: forward_prop(x, w1_init, b1_init, 
                                              w2_init, b2_init, w3_init, b3_init,
                                              activation_function, i=i)

In [91]:
print(forward_prop_init(x1, 6))
print(forward_prop_init(x2, 6)) # Sacar os resultados intermedios

[[-0.91590016]
 [-0.80493961]
 [-0.91590016]]
[[-0.98652085]
 [-0.9981635 ]
 [-0.98652085]]


In [92]:
np.set_printoptions(suppress=True)

delta_3_1 = error_derivative(t1, forward_prop_init(x1, 6))*activation_derivative(forward_prop_init(x1, 5))
delta_2_1 = w3_init.T@delta_3_1*activation_derivative(forward_prop_init(x1, 3))
delta_1_1 = w2_init.T@delta_2_1*activation_derivative(forward_prop_init(x1, 1))

delta_3_2 = error_derivative(t2, forward_prop_init(x2, 6))*activation_derivative(forward_prop_init(x2, 5))
delta_2_2 = w3_init.T@delta_3_2*activation_derivative(forward_prop_init(x2, 3))
delta_1_2 = w2_init.T@delta_2_2*activation_derivative(forward_prop_init(x2, 1))


print(delta_1_2)

[[-0.00001666]
 [-0.00001978]
 [-0.00001666]]


In [93]:
derivative_E_w3 = delta_3_1@(forward_prop_init(x1, 4)).T + delta_3_2@(forward_prop_init(x2, 4)).T
derivative_E_w2 = delta_2_1@(forward_prop_init(x1, 2)).T + delta_2_2@(forward_prop_init(x2, 2)).T
derivative_E_w1 = delta_1_1@(forward_prop_init(x1, 0)).T + delta_1_2@(forward_prop_init(x2, 0)).T

w3_new = w3_init - learning_rate*derivative_E_w3
w2_new = w2_init - learning_rate*derivative_E_w2
w1_new = w1_init - learning_rate*derivative_E_w1

derivative_E_b3 = delta_3_1 + delta_3_2
derivative_E_b2 = delta_2_1 + delta_2_2
derivative_E_b1 = delta_1_1 + delta_1_2

b3_new = b3_init - learning_rate*derivative_E_b3
b2_new = b2_init - learning_rate*derivative_E_b2
b1_new = b1_init - learning_rate*derivative_E_b1


print(w3_new)
print(w2_new)
print(w1_new)
print(b3_new)
print(b2_new)
print(b1_new)


[[0.99703633 0.9977484 ]
 [3.01431372 0.98168546]
 [0.99971282 1.00040847]]
[[1.01730444 4.02851932 1.01730444]
 [1.00467751 1.00771893 1.00467751]]
[[1.0187207  1.01871904 1.01871904 1.01871737]
 [1.03358917 1.03358719 2.03358719 1.03358521]
 [1.0187207  1.01871904 1.01871904 1.01871737]]
[[1.00198208]
 [1.03177312]
 [0.99930442]]
[[1.0374494 ]
 [1.01017306]]
[[1.0187207 ]
 [1.03358917]
 [1.0187207 ]]
