In [23]:
import numpy as np

data = np.array([[0.7, -0.3], [0.4, 0.5], [-0.2, 0.8], [-0.4, 0.3]])

def rbf(x):
    basis = [[0, 0], [1, -1], [-1, 1]]
    distances = np.array([np.linalg.norm(x-k) for k in basis])
    return list(np.exp(-(distances**2)/2))

X = np.array([[1]+rbf(d) for d in data]) # Add 1's in first collumn to multiply with bias
Z = np.array([0.8, 0.6, 0.3, 0.3])
lam = 0.1
X

array([[1.        , 0.74826357, 0.74826357, 0.10126646],
       [1.        , 0.81464732, 0.27117254, 0.33121088],
       [1.        , 0.71177032, 0.09632764, 0.71177032],
       [1.        , 0.8824969 , 0.16121764, 0.65376979]])

In [26]:
W = np.linalg.inv((X.T)@X + lam*np.identity(4)) @ X.T @ Z
X.T

array([[1.        , 1.        , 1.        , 1.        ],
       [0.74826357, 0.81464732, 0.71177032, 0.8824969 ],
       [0.74826357, 0.27117254, 0.09632764, 0.16121764],
       [0.10126646, 0.33121088, 0.71177032, 0.65376979]])

In [25]:
W @ X.T

array([0.75843541, 0.51231759, 0.3090472 , 0.38628554])