In [1]:
import numpy as np

w1_init = np.array([[1, 1, 1, 1], [1, 1, 2, 1], [1, 1, 1, 1]])
b1_init = np.array([[1], [1], [1]])
w2_init = np.array([[1, 4, 1], [1, 1, 1]])
b2_init = np.array([[1], [1]])
w3_init = np.array([[1, 1], [3, 1], [1, 1]])
b3_init = np.array([[1], [1], [1]])

activation_function = lambda x: np.tanh(0.5*x - 2)
activation_derivative = lambda x: 0.5 - 0.5*(np.tanh(0.5*x - 2))**2

error_derivative = lambda t, o: -(t-o)

x1 = np.array([[1], [1], [1], [1]])
x2 = np.array([[1], [0], [0], [-1]])

t1 = np.array([[-1], [1], [-1]])
t2 = np.array([[1], [-1], [-1]])

learning_rate = 0.1

In [2]:
def forward_prop(x0, w1, b1, w2, b2, w3, b3, activation, i=6):
    # Layer 1
    z1 = w1@x0 + b1
    x1 = activation(z1)

    # Layer 2
    z2 = w2@x1 + b2
    x2 = activation(z2)

    # Layer 3
    z3 = w3@x2 + b3
    x3 = activation(z3)
    outputs = [x0, z1, x1, z2, x2, z3, x3]
    return outputs[i]

In [3]:
forward_prop_init = lambda x, i: forward_prop(x, w1_init, b1_init, w2_init, b2_init, w3_init, b3_init, activation_function, i=i)

In [4]:
print(forward_prop_init(x1, 6))
print(forward_prop_init(x2, 6)) # Sacar os resultados intermedios

[[-0.91590016]
 [-0.80493961]
 [-0.91590016]]
[[-0.98652085]
 [-0.9981635 ]
 [-0.98652085]]


In [5]:
delta_3_1 = error_derivative(t1, forward_prop_init(x1, 6))*activation_derivative(forward_prop_init(x1, 5))
delta_2_1 = w3_init.T@delta_3_1*activation_derivative(forward_prop_init(x1, 3))
delta_1_1 = w2_init.T@delta_2_1*activation_derivative(forward_prop_init(x1, 1))

delta_3_2 = error_derivative(t2, forward_prop_init(x2, 6))*activation_derivative(forward_prop_init(x2, 5))
delta_2_2 = w3_init.T@delta_3_2*activation_derivative(forward_prop_init(x2, 3))
delta_1_2 = w2_init.T@delta_2_2*activation_derivative(forward_prop_init(x2, 1))

delta_1_2

array([[-1.66619254e-05],
       [-1.97816249e-05],
       [-1.66619254e-05]])

In [6]:
w3_new = w3_init - learning_rate*(delta_3_1@(forward_prop_init(x1, 4)).T + delta_3_2@(forward_prop_init(x2, 4)).T)
w2_new = w2_init - learning_rate*(delta_2_1@(forward_prop_init(x1, 2)).T + delta_2_2@(forward_prop_init(x2, 2)).T)
w1_new = w1_init - learning_rate*(delta_1_1@(forward_prop_init(x1, 0)).T + delta_1_2@(forward_prop_init(x2, 0)).T)

b3_new = b3_init - learning_rate*(delta_3_1 + delta_3_2)
b2_new = b2_init - learning_rate*(delta_2_1 + delta_2_2)
b1_new = b1_init - learning_rate*(delta_1_1 + delta_1_2)

print(delta_1_1)


[[-0.18719036]
 [-0.33587187]
 [-0.18719036]]
